services:
  - type: web
    name: property-dashboard
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -p $PORT
    envVars:
      - key: NODE_ENV
        value: production