export interface Property {
  id: string;
  address: string;
  clientName: string;
  sellingAgent: string;
  loanNumber?: string;
  basisPoints?: number;
  closingDate?: string;
  underContractPrice?: number;
  startingListPrice?: number;
  currentListPrice?: number;
  status: 'Active' | 'Under Contract' | 'Pending' | 'Closed' | 'Hold';
  propertyType: 'Single Family' | 'Duplex' | 'Rental' | 'Commercial';
  isRented: boolean;
  notes: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  tasks: Task[];
  contingencyDates?: ContingencyDates;
  createdAt: string;
  updatedAt: string;
  listingDate?: string; // When property was first listed
  lastPriceReduction?: string; // Last time price was reduced
}

export interface ContingencyDates {
  earnestMoney?: string;
  inspection?: string;
  title?: string;
  appraisal?: string;
  lending?: string;
  occupancy?: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  dueDate: string;
  priority: 'Low' | 'Medium' | 'High' | 'Urgent';
  status: 'Pending' | 'In Progress' | 'Completed';
  category: 'Pre-Listing' | 'Under Contract' | 'Documentation' | 'Contractor' | 'Agent Follow-up' | 'Legal' | 'Inspection' | 'Price Review' | 'Other';
  assignedTo?: string;
  completedAt?: string;
  completionNotes?: string;
  propertyId: string;
  taskType: 'pre-listing' | 'under-contract' | 'price-review';
  isAutoGenerated?: boolean; // For automatic price reduction tasks
}

export interface DashboardStats {
  totalProperties: number;
  activeListings: number;
  underContract: number;
  pendingTasks: number;
  urgentTasks: number;
  avgDaysToClose: number;
}