import { Property, Task } from '../types';

export const mockTasks: Task[] = [
  // Pre-listing tasks
  {
    id: '1',
    title: 'Professional Photography',
    description: 'Schedule professional photographer for listing photos',
    dueDate: '2025-01-20',
    priority: 'High',
    status: 'Pending',
    category: 'Pre-Listing',
    propertyId: '4',
    taskType: 'pre-listing'
  },
  {
    id: '2',
    title: 'Property Staging',
    description: 'Coordinate with staging company for property setup',
    dueDate: '2025-01-22',
    priority: 'Medium',
    status: 'Pending',
    category: 'Pre-Listing',
    propertyId: '4',
    taskType: 'pre-listing'
  },
  {
    id: '3',
    title: 'MLS Listing Creation',
    description: 'Create and upload MLS listing with photos and details',
    dueDate: '2025-01-25',
    priority: 'High',
    status: 'Pending',
    category: 'Pre-Listing',
    propertyId: '4',
    taskType: 'pre-listing'
  },
  
  // Under contract tasks
  {
    id: '4',
    title: 'Schedule Home Inspection',
    description: 'Contact inspection company for 123 Main St property',
    dueDate: '2025-01-18',
    priority: 'High',
    status: 'Pending',
    category: 'Under Contract',
    propertyId: '1',
    taskType: 'under-contract'
  },
  {
    id: '5',
    title: 'Follow up with Buyer Agent',
    description: 'Check status of loan approval for Oak Avenue property',
    dueDate: '2025-01-16',
    priority: 'Urgent',
    status: 'Pending',
    category: 'Under Contract',
    propertyId: '2',
    taskType: 'under-contract'
  },
  {
    id: '6',
    title: 'Prepare Closing Documents',
    description: 'Gather all necessary paperwork for Pine Street closing',
    dueDate: '2025-01-20',
    priority: 'Medium',
    status: 'In Progress',
    category: 'Under Contract',
    propertyId: '3',
    taskType: 'under-contract'
  },
  {
    id: '7',
    title: 'Title Company Coordination',
    description: 'Confirm title search completion and clear title',
    dueDate: '2025-01-19',
    priority: 'High',
    status: 'Pending',
    category: 'Under Contract',
    propertyId: '1',
    taskType: 'under-contract'
  },
  {
    id: '8',
    title: 'Appraisal Follow-up',
    description: 'Ensure appraisal is scheduled and completed on time',
    dueDate: '2025-01-21',
    priority: 'High',
    status: 'Pending',
    category: 'Under Contract',
    propertyId: '2',
    taskType: 'under-contract'
  },
  
  // Price review tasks (auto-generated)
  {
    id: '9',
    title: 'Price Review - 30 Days on Market',
    description: 'Property has been on market for 30 days. Consider price reduction or document reason for maintaining current price.',
    dueDate: '2025-01-18',
    priority: 'High',
    status: 'Pending',
    category: 'Price Review',
    propertyId: '5',
    taskType: 'price-review',
    isAutoGenerated: true
  },
  {
    id: '10',
    title: 'Price Review - 60 Days on Market',
    description: 'Property has been on market for 60 days. Strong recommendation for price adjustment or enhanced marketing strategy.',
    dueDate: '2025-01-20',
    priority: 'Urgent',
    status: 'Pending',
    category: 'Price Review',
    propertyId: '4',
    taskType: 'price-review',
    isAutoGenerated: true
  }
];

export const mockProperties: Property[] = [
  {
    id: '1',
    address: '123 Main Street, Springfield, IL 62701',
    clientName: 'Johnson Investment Group',
    sellingAgent: 'Sarah Johnson',
    loanNumber: 'LN-2024-001',
    basisPoints: 150,
    closingDate: '2025-02-15',
    underContractPrice: 285000,
    startingListPrice: 299000,
    currentListPrice: 289000,
    status: 'Under Contract',
    propertyType: 'Single Family',
    isRented: false,
    notes: 'Beautiful 3BR/2BA home with updated kitchen. Buyer pre-approved with excellent credit.',
    coordinates: { lat: 39.7817, lng: -89.6501 },
    tasks: mockTasks.filter(task => task.propertyId === '1'),
    contingencyDates: {
      earnestMoney: '2025-01-10',
      inspection: '2025-01-18',
      title: '2025-01-25',
      appraisal: '2025-01-30',
      lending: '2025-02-05',
      occupancy: '2025-02-15'
    },
    createdAt: '2024-12-01',
    updatedAt: '2025-01-15',
    listingDate: '2024-12-15',
    lastPriceReduction: '2025-01-05'
  },
  {
    id: '2',
    address: '456 Oak Avenue, Springfield, IL 62702',
    clientName: 'Miller Family Trust',
    sellingAgent: 'Michael Chen',
    loanNumber: 'LN-2024-002',
    basisPoints: 200,
    closingDate: '2025-01-28',
    underContractPrice: 320000,
    startingListPrice: 335000,
    currentListPrice: 325000,
    status: 'Under Contract',
    propertyType: 'Single Family',
    isRented: false,
    notes: 'Corner lot property with large garage. Some minor repairs needed before closing.',
    coordinates: { lat: 39.7831, lng: -89.6498 },
    tasks: mockTasks.filter(task => task.propertyId === '2'),
    contingencyDates: {
      earnestMoney: '2025-01-05',
      inspection: '2025-01-15',
      title: '2025-01-20',
      appraisal: '2025-01-22',
      lending: '2025-01-25',
      occupancy: '2025-01-28'
    },
    createdAt: '2024-11-15',
    updatedAt: '2025-01-14',
    listingDate: '2024-11-20',
    lastPriceReduction: '2024-12-20'
  },
  {
    id: '3',
    address: '789 Pine Street, Springfield, IL 62703',
    clientName: 'Rodriguez Properties LLC',
    sellingAgent: 'Jennifer Davis',
    loanNumber: 'LN-2024-003',
    basisPoints: 175,
    closingDate: '2025-01-25',
    underContractPrice: 195000,
    startingListPrice: 210000,
    currentListPrice: 199000,
    status: 'Pending',
    propertyType: 'Duplex',
    isRented: true,
    notes: 'Investment property with existing tenants. Rental income $1,800/month.',
    coordinates: { lat: 39.7825, lng: -89.6485 },
    tasks: mockTasks.filter(task => task.propertyId === '3'),
    contingencyDates: {
      earnestMoney: '2024-12-20',
      inspection: '2025-01-10',
      title: '2025-01-15',
      appraisal: '2025-01-18',
      lending: '2025-01-22',
      occupancy: '2025-01-25'
    },
    createdAt: '2024-10-20',
    updatedAt: '2025-01-13',
    listingDate: '2024-10-25',
    lastPriceReduction: '2024-11-25'
  },
  {
    id: '4',
    address: '321 Elm Street, Springfield, IL 62704',
    clientName: 'Thompson Estate',
    sellingAgent: 'Robert Martinez',
    basisPoints: 125,
    startingListPrice: 245000,
    currentListPrice: 245000,
    status: 'Active',
    propertyType: 'Single Family',
    isRented: false,
    notes: 'Recently renovated home with modern updates. Great curb appeal.',
    coordinates: { lat: 39.7810, lng: -89.6520 },
    tasks: mockTasks.filter(task => task.propertyId === '4'),
    createdAt: '2024-12-10',
    updatedAt: '2025-01-15',
    listingDate: '2024-11-20' // 60+ days on market
  },
  {
    id: '5',
    address: '654 Maple Drive, Springfield, IL 62705',
    clientName: 'Anderson Holdings',
    sellingAgent: 'Lisa Thompson',
    basisPoints: 190,
    startingListPrice: 285000,
    currentListPrice: 279000,
    status: 'Active',
    propertyType: 'Single Family',
    isRented: false,
    notes: 'Move-in ready home with modern amenities. Great location near schools.',
    coordinates: { lat: 39.7840, lng: -89.6510 },
    tasks: mockTasks.filter(task => task.propertyId === '5'),
    createdAt: '2024-11-25',
    updatedAt: '2025-01-12',
    listingDate: '2024-12-18', // 30+ days on market
    lastPriceReduction: '2025-01-10'
  }
];